#+STARTUP: indent
#+FILETAGS: writing fiction "prepper"
* Sam meets Alex
Sam was searching for the next big thing when he ran into Alex at TechSpo Labs conference in San Diego. Sam had been searching for the next big thing for 8 years, or in other words; for 3 girlfriends, 4 apartments, 3 Burning Mans, and 8,762 nitro cold brews Sam has been searching for a job.

When you have 42.7 million in investments with an average return of 10.7%, you can take you time about things. In addtion for Sam, a product of an American upper class background, a job was a calling, a devotion, a reason d'etre, and so he was quite picky about it. When you don't have to work, it's hard to find a job.
# Cut

It was considered crass to talk about money; to talk about how much you had netted out from stock options in your startup, even though that was the final goal, just as it is considered crass to talk about death and philosophy as if you could be bothered. It was sad that you couldn't talk about real things with people anymore, politics, money, power, sickness, death, it was all taboo and climate change was one of them too now.
# Cut or revise

You just kind of knew, who was who and who had cashed out and how much. It was like a running leaderboard that was constantly in your mind or blasting the finaly tally in the sky. Something nobody really thought about or admitted to themselves was how most of the time it was just luck, it was just the luck whether you'd made it or failed. Post fact, they attributed it to technical wizardry, resiliance, their 'willingness to fail', risk tolerance, but generally it was most about where you were when and who you knew; of course ruthless business practices helped too but no one talked about these things just like no one really talks about anything in a bald faced no nonesense way. Everything you learn is mostly fairy tales. But moving on...
# Cut or revise
# My tone and subject matter is reminding me of that english writer... the one about fuck it will look it up later

Sam was invited to TechSpo pre-party at a founder's house up on a hill overlooking the beach and the ocean. It was one of those southern california nights; 72 degrees farenheit, zero humidity, with cool westerly breeze that reminded you of the Greek islands,  wispy stratospheric clouds highlighing the sky and the setting sun across the bay. It was heaven and perfection on earth for those who had eyes to see, and heart to feel.

But Sam was busy trying to find the next big thing, he flittered from group to group listening in on conversations and saying hi to people he knew. He was in his late thirties and worried that he might be running out of time to change the world, to make a hundred millions dollars, and to make a mark of his passage on the earth. Because that was the goal, get rich while changing the world for the better. What mark does the cloud leave when it turns to rain to nourish the earth?

While thus scouring the party for tidbits of gossip, news, and the next big thing Sam spied Alex on the balcony. Alex was alone, staring off into the western horizon watching the last bit of the light as it disappeared over the pacific ocean, as the first stars began to glimmer in the expanse of the darkness above them.

"Fancy meeting you here!" Sam called out. Sam didn't really like Alex but he had an instatiable need to keep tabs on people and hadn't seen him in years. Alex had dropped out of the scene completely and Sam's curiosity drove him; things needed to be labeled, categorized and put in their boxes so they could be closed and filed away. Besides, Alex was an influential tech guru, practically a billionaire, and a super successful guy in general.

Alex did not turn around or respond. Sam determined, walked up to him about to yell out: "Hey Alex!" but before he could get the words out, he noticed that tears were streaming down Alex's face.

"There's so much to lose," Alex said. "We have ten, fifteen years before the shit really hits the fan. Before it comes crashing down."

Sam had heard that Alex wasn't the same after his last trip to South American on a Ayahusca tour, but he did not expect to be talking to a doomer. Ugh, they were just the worst. They made you feel quilty for just breathing and being lucky enough to be born in the western hemisphere.

"You were in Cali last year right? The flooding, fires, the mass die offs, fucking Biblical shit and I thought it would be a wake up call finally," he continues, "We're the most connected, affluent, influential... the highest concentration of PhDs in the world is in your fucking zip code. But nothing. Nothing but stock options, who's banging who, who's gotten Series C funding, and everyone trying to cash out."

"I thought," he continued, "if enough people understood, we'd reach a critical mass, a turning point right? Only 3% of the population needs to be mobilized for cultural change, that's a trusim now, right? There's so much we can do still, there's so much we can do collectively to mitigate a part of what's coming down the pipeline. But no one wants to hear it, no one wants to face any of it. It's too hairy and uncomfortble. The captains of industry and the best they can come up with is to make more climate change startups, the best and brightest in the world are nothing more than a bunch of faggots running around in a continual circle jerk."

"I don't get it. So we're not going to reach the 1.5 Celcius target but we still have 30 years until..."
# Add a non-sequitor here, show how Sam tries to divert and deflect the conversation in multiple ways

Alex rolled his eyes at him, "I'm tired of your dumb shit Sam, you don't think the Pentagon and US goverment has contingency plans for what's coming? Do you know why Bill Gates is the 2nd largest agricultural land owner in North America? Do you know where Peter Thiel, and Larry Ellison's Doomsday bunkers are? Anybody who knows what's going on has already made plans, everything else is make believe at this point."

Alex shoved a manuscript in his face saying, "Take this, it may at least open your eyes!" Alex then stomped away.

The only thing that kept Sam from shrugging all this off as another delusional fringe new-age like phastasmogoria cult thinking that's been proliferating more and more lately like a virus was what he knew of Alex. Alex was a brilliant technologist who in the last fifteen years had been at the cusp of every new and profitable technological wave. He had gotten on the groundfloor with AI, especially the hardware side, he had championed the electric vehical shift and was a board member of tesla; these among numerous other successes that had proven Alex to be a far sighted thinker, one who could see the swelling of the wave and feel the tectonic shifts before they were evident to the population at large.

The manuscript Alex had thrust upon him was seemingly just a copy of the 2023 IPCC (Intergovernmental Panel on Climate Change) report, but on closer insepection it turned out to be a smuggled copy of an earlier draft that had not been released. Included in this unreleased document were printed email threads of the principle scientists and drafting committees, along with pages and pages of transcribed meeting notes, and additional studies.

Sam was aware of the dire warnings of the 2023 report from the New York Times: "Climate Change Is Speeding Toward Catastrophe. The Next Decade Is Crucial, U.N. Panel Says," but he hadn't yet gotten around to reading the article, it was on his ever growing reading list. He had scrolled past and was already absorbed on the hundred bit of interesting tid bit of datum before he lost the thread.
# Add details on what he saw while scrolling, and what he clicked on, and what he spent his time and attention on here

* Sam sees the white rabbit
# I think something else needs to happen here, he goes to rejoin the party and just files it away for a while and keeps living his life and we see him with his girlfriend, and just list out his life like an ai calendar schedule or something. But something happens that makes him dig out the manuscript

# Sam goes into the hole and he finds the facts or the things that were evident but he was too busy to think about, but it's all there really, there's nothing hidden, nothing secret, but it's like everyone thought it was someone else's job to figure out a fix. I mean it's been in the news since 1980 fuck

# He tries to go back to normal life but he can't, it's that disjunct of the everyday with the immensity of the reality that you have, that I would like to describe in some way or dramatize, because that's the thing I'm trying to articulate really, that's the feeling that I have, that's the fucking thing that I want to express and yell out over the rooftops

Sam walked back towards the house, the music, and the party, trying to make out the words in the manuscript, in search of a steady reading light.
# Add physical detail of him walking through the house, past the dance floor, pool, the stobbing lights, the kitchen with drugs, each part of the party is an invitiation to linger and forget, like Odysseus but Sam pushes on and it's a real battle
All the while reading the words of the manuscript Alex had pushed into his hands. Sam was not and never was an environmentalist, he was a technologist who believed in the distinctly San Palo Alto version of capitalist liberal tecno-optimism; there was a rational and likely technological solution to most problems and they could be solved by the free-market mechanism of free flowing capital moving towards the optimal solution set of entrepuerial enterprise.

Sam was about to chuck the document Alex had pushed into his hands, thick and heavy as a telephone book somewhere and get back to the party but as Sam was skimming through, this passage stuck with him and reverberated in his mind: "We are in a precipitous moment in our climate history, where what we do or fail to do in the next 10 years will inevitably chart the course of earth's climatic future for the next millenia. If we fail to act, we will unleash the climate tipping points that will flip earth's climate into a new regime that no human has experienced in the 2 million years of our evolution."
# Need a better catch phrase here like in the bear; 'every second counts,' 'let it rip'

# The above quote is good, I'm impressed with me just winging that out of the blue. Possibly turn this into an argument or email thread of the scientists that compells Alex to read on, and possibly track down the scientist to try to talk to him. This is a good idea, an dramatic email exchange between the scientist arguing about something heatedly

But as he sat in kitchenette bench next to the olypmic sized infinity pool, under a dome of warm LED lighting in wood paneled luxury imported fromt dying Indonesian hard wood forest, Sam read on and possibly for the first time, a glimmer of the thought began to grow in him like a seed, or a drop of dye dropped into a solution, that maybe, possibly, just maybe, there was a chance that tomorrow would not be better than yesterday; that maybe civilization and progress was not a linearly rising tide lifting all boats higher.

For the duration of the evening Sam sat in the same spot as the party goers danced, drank, yelled coversation into each others ears over the noise of the electronic music and jostled around him reading through the 341 pages of the manuscript.
# Need to summarize Sam's takeaway from the manuscript here, and hint at the scientist's anger, desperation, and the politics of compromise

As the music cut and the revelers were beginning to disperse, Sam flipped closed the last page of printout glancing around at the detritus of the party. There were a few groupings of people still clinging on to the illusion that the party was still in progress; the bitter enders trying to get the party to continue among the empty squashed cups and half drunk bottles. Sam looked up and said to no one: "I found the next big thing." The girl sitting next to him, head collapses on arm, seemingly passed out leaned over and vomited quietly into his lap.

* Sam goes into the rabbit hole
Sam learned of the possible shutdown of the Atlantic Meridional Overturning Circulation, the moulins in the Greenland icesheet, the methane hydrates in the ocean floor sequestering an estiamted 2 gigatons of carbon, the thawing of the permafrost in Siberia, the ocean carbon cycle and how after a certain temp limit the ocean would turn from a carbon sink to a carbon producer, there was just so much, and so much unexpected interconnected factors and feedback cycles like the albedo effect
# Add more summarized details here

It became blindingly clear to Sam that it was just a matter of time. Humanity had lit the fuse of a ticking planetary time bomb and it was just a matter of time until the slumbering monster awoke like it has so often before in the geological past, lurching from one climate regime into another and shaking everything off like fleas. Most people would die either quickly, some military scenarios commissioned by the Pentagon called envisioned up to 2 billion deaths once 2C was breached due to famine and war.

The more Sam read and became immersed in the literature the more he was shocked at how obviously dire things were, but the world kept going, you still went on vacation and still worried about retirement and still socked in $200 a month for your child's 429, the disconnect from what he knew and the reality around him was uncanny and bizarre and unsettling.

He was like a man who had been issued a terminal diagnosis, who's mouth is full of ashes but must maintain a pretense that any of the rest matters; the mortgage, the burnt toast, the spilt milk.

It was so unsettling that he wondered if he wasn't cracking going crazy. Was this real, did the world continue on with the knowledge that everything would come crashing down on our watch, that life as we know it was done and no longer feasible, that we're already living in the vestiges of the fumes of the old world, and the new one that was to be born in flames out of the old? Was this what was like to live in the days prior to the great world wars, a sense of immpending doom on the horizon, but the merry go round continuing to circle brightly with it's gay lights and music.

# Want to do some reading and research on the topics above, want this to be drawn from real studies with appendix. But more than really getting bogged down here with details and science, maybe it can be just quotes, blurbs, titles, social media posts that show each
# A new method or something needs to change here
# Add the different planetary epochs that are relevant, I want this to also be an educational
# Paleocene-Eocene Thermal Maximum PETM
# Add a scene or story line about a help group talk theraphy session? I am in climate grief and I don't know what to do

The top climate scientists in the world were privately in a depressive panic at the unprecedented and rapid pace of change their instruments were measuring. Some took to drinking, some took to activism, others buried themselves grimly deeper into the the work like foot soldiers in a war.
# Add the complete lack of progress here, highlight Carl Sagan and Jim Hansan's congressional testimony with exerpts in the 1980s

The burden of knowledge was anathema to them. There were those who, completely disillusioned with the state of things had moved into hermit like seclusion in the woods or joined Luddite nomadic communities in the plains of Mongolia.

There were more and more articles about 'climate grief' and 'climate anxiety.' The scientist were the canaries in the coalmine, the Cassandras who could see clearly see the coming calamity but were powerless to do anything in their knowledge and so they suffered, often alone and isolated.

Sam reaches out to a friend who is a friend of someone who knows one of the ICPPs reviewers on climate paleontology and had a thread of forceful emails with the ICPP planning committee on the manuscript Alex thrust on him that fateful night. They correspond briefly and Peter emails Alex; "There's a thing I'm going to be around x area for, why don't you come crash it and we can talk."
# Show and detail the comment thread

Peter was among the last of the old time academics, these were ivy league trained scientists who forsook possible million dollar careers as AI engineers and quants at hedge funds, possibly the greatest collection of altruistic minds sharpened to a find point of occam's razor, trained with the most powerful supercomputers in the world. It seemed foolish not to take these people seriously.  Basically saying that we're about to hit the proverbial iceberg in the ocean in the next 5 to 10 years unless we change course.

The scientists no longer went to parties, or social events, they felt that they could not make small talk, or continue to play the game of polite boroque western civilization games when the whole thing was heading off a cliff faster and faster than they could report.

When their neighbors talked about spending their summers in Spain or flying to the Alps for the holidays or  buying a condo in South Carolina or Florida, the scientists tried to smile, they choked down their instictive responses, and almost embarrassed they nodded brightly, as if a child of six had asked them if God existed, if there was life after death, if Santa Claus would visit them in the night and leave presents.
# Dramatize with Sam as suggested below
# It might actually be a decent scene vs narration, where maybe Sam is the one who chokes, maybe it's his girlfriend

Sam inevitably tried to broach the subject among his circle, but was met with incredulity, impatience, and pure denial. At a cocktail party, whatever that is somewhere in the US, eastcoast ivy league vibes, dark sweater knits, wood paneled library, small paneled windows looking out into the snow falling, quieting and dampening the dark afternoon with their floating falling shadows; the tone is muted, it's pre-Thanksgiving social with drinks. Sam picks at the spread, expensive french cheese and local chartuerie board, beautifully laid out, with sculptured veggie plates and dipps, crackers, breads, olives, and pates that took up every inch of the large rustic table. It must have cost a pretty penny. Using metal tongs, Sam placed pieces of prociutto, melon, chees and a few crackers on his plate absent mindedly.

Sam's mind was on the latest weather freak weather disaster that hit the east coast, a late season hurrican that pounded the major metros causing widespread flooding, with dozens dead and missing in New York, Boston, and Philly. The videos were frightening, lower Manhattan and parts of Brooklyn basically under water with over 10 feet of storm surge. The Freedom Tower and Empire State windows blown out by category 6 winds and debris. Just another 500 year storm in a year of record breaking heat and atomospheric anamolies. Shit was getting real, but all you heard were the usual talking points and the world carried on.

Andrea approached, "And here is our west coast outcast, come in from the storm!" They hug one of those one armed hugs and catch up on each other's doings since last year.
# I kinda feel like it could go on like this forever, not necessarily happy with this approach, like how do I set up the scenes in a simple way or tell the story in a efficient way instead of doing all this.  Maybe just need to write it out, get lost, and do it the wrong way first, not sure but doesn't help me feeling like this

Sam has been making it a habit of broaching the topic of climate change regularly during conversation with people he was somewhat close to, people who he thought would be open to having an open discussion about the topic. It was easy enough to bring up because it would always come up with what he was doing.

"What are you up to these days Sam?" Andrea asked.

"I started the climate action podcast, I've been putting that out every week. You know, but it's hard to get traction, the market's too splintered and there's just so much out there.

# I would like to show a few different types of reactions, all of them sympathetic but all of them not helpful

This is the knowledge that cleaved, the dark presentiment of a future tragedy that set you apart.

Sam began to understand the need that Alex had felt, the need to warn, to convince, to show the people around him that we were on the fucking titanic and we have to change course 20 fucking years ago. That was really the cherry on top, the complete and total disconnect of people and everyday life from the cold hard reality of things. He felt like someone trapped in a Philip K. Dick story, where everyone lived a white picket fence fucking life but he knew that the asteroid was coming to hit earth and we were the dinosaurs going to be decimated in place.
# Show conversation between Sam and another 'ratonal' person, Sam trying to convince him of the future but the guy just shruggs it off
# Could be part of his attempt at activism, show the kind of limitedness of it here, they just ask for money and for you to join a mailign list where they ask for more money

# Would like to show something about collective action, how we don't know what that is, and we're no longer practiced at it, how the collective ideals of the early tech revolution was smashed and destroyed and it is what it is now
# Maybe Sam tries to act, kind of half heartedly but fails, would be good to have a bit of comedy of errors here

# Thinking about this and Sam would try to do what the current entrepreneurs are doing, he would try to solve it while making money, he would start a climate startup or try to join one
# How can I dramatize a synopsis of a venture without going too deep into it and side tracked?  Maybe a podcast is a better idea

* Sam is depressed
Sam hit the snooze on his analog for the 4th time which highly unusual. Sam had not deviated from his 'optimial morning routine for high performance' in the last five years, weekday, weekend, holiday, Christmas morning, he had religiously followed it. Out of bed by 5am, cold morning water plunge for 5 minutes, morning 20 minute meditaion session on empty breakfast where he set the day's intention consciously, Then at sunrise, 6:17am this morning he took a walk facing towards the west, if and when weather permitting getting sunlight to hit his skin to activate the time setting genes in his mitochondria. Breakfast was matcha tea which has shown to improve focus without the caffiene crash. The bottom 3 shelves of his fridge was filled wihth cartons of the new meal replacement cartons called; rows and rows of perfectly aligned meal replacement drink called Nutly made from single source organically certified varieties of 6 south american nuts, fortified by soluable protein manufactured by ai computer models.
# Want to make fun of this but not belabor it or make it boring. The above is just a list that's boring, need to solve it in a different way

Sam suddenly found that he had lost interest in all the things he used to once enjoy. Even the award winning nitro brew with locally sourced and grown raw milk called rocket fuel at Bola's did not offer joy or satistfaction. The activities and things he used to enjoy fell flat, the emotional color seemed to drain out of the world; bouldering at the Movement gym, the entire design and tech sector, all the cool things, that he'd spend the last twenty years eating, living, and breathing seemed like part of the disease and misuse of everything. He could not reconcile the new found heavy truth of what he now knew with the everyday and it's concerns. He was in a classic Cassandra's bind. What does one do now?
# Like all of this is telling instead of showing... like this whole thing needs to be rewritten, like how do I dramatize all of it in events instead of just narrating it?

There were days where he just doomscrolled the day away in bed, watching the colors burn and fade through the window curtains. Maybe if Sam had actually let himself feel, had been able to integrated the emotional and pyschological baggage of this existential knowledge and incorporate it, if he had been able to let it in and move into and through the darkness, Sam might have taken a different path. As it was, Sam stared into the horror of civilizational collapse, a thousand years of suffering, and decided; "I gotta save myself. I have to lookout for number one."
# This turning point or transition could be better, like maybe he things or believes that he's going to be an island or a beacon in the desert somehow, he will help to restart the world and humanity. By helping himself he could help the world, by being selfish he was serving the greater good, this is the same logic that current climate startups and silicon valley implicitly believes and it's sickening.

# Maybe add a short section on how he tries to do the right things and join a climate change group, but they are bogged down in fundraising and he gets assigned to cold call people and after a week of this he's had enough, and how he meets the activists and the radicals, and the hippies and he doesn't belong or fit with any of them...

* Sam's next big thing
# Sam is on a messiah kick, he feels like he's discovered something new, important, and actionable here and is motivated to act
# He starts a podcast to proselytize and move people, he hires a team, he gets no traction, the silicon valley and scientist he's able to get on don't go to script, and the podcast start veering off into a dark prepper kind of road, but that's what gains traction not the climate change policy activism stuff
# He decides to venture fund a climate startup and goes looking for companies that can change the game but it's just games he realizes
Energized with purpose and new found knowledge, Sam burns into a whirlwind of acivtiy and work.  He couldn't wait to make a difference in the climate change movement, and be part of something that would be worthwhile and important.

Most of the work involved in calling people; Sam calls his accountant to set up a tax deductible non-profit and asks him to name it "GSDC" for Getting Shit Done on Climate and to divert 200k to it's funds.  Sam realized that this was what he had been missing, a purpose, a cause larger than himself and he was eager to get to do real work.  Sam feels great, he hasn't been this excited or sure of anything in eight years, he vigorously rolls up his sleeves to get to work, Sam calls more people. He gets on call after call after call, the more calls he gets on the more important he feels, this is going to be big he thinks, this is going to make a difference, he sets up meetings, forms a team, and hire this and that person for this project. They brainstorm and decide that a podcast is needed to make the public aware and so serious climate discussions can be had.

Sam and his producer have set up a live stream podcast for a panel of experts to come and discuss the issue, and what must be done to get the world back on track for 1.5C warming. Sam's team is able to get some of the top climate scientists from all over the world to join.

"Thank you for joining our inaugural podcast on 'Getting Shit Done,'
# Something is blocking me from writing this out, it's like I could do it but I'm not sure what the reason would be like what the point is... maybe think this through more
# It's a podcast where, each of them kind of review what they've done and why they should be taken seriously, an intro and quickly goes off the rails
# Because they one of the guests knows Sam and where he's made his money?
# What would be cool, fun here? It's like everything is a chore and have to, how to escape that
# What if they just veer off into something completely stupid
# Take a look at the MOC YT video and kinda riff off that, with Sam and another guest kinda getting off the rails
# Even with all the paid marketing, the podcast never gets off the ground, maybe the podcast itself is something nonesensical, like shark tank for climate change
# The idea is okay... but doesn't really do it for me
# So what else can it be? Where else can we take it?
# What would be cool? What if they have a scientist on and it starts real, but then the scientist starts talkinga about his preparations
# I think maybe playing with the form could offer relief here, experiment with unexpected forms and techniques to get the idea across vs forcing yourself to write by rote, with no energy or feeling

# I think the issue is, how can I reflect and show a change in the character, without having to show and dramatize the entire sequence of actions? Maybe it's something that I've never learned but it's a technical issue.  I have to be able to show a dramatic scene that encapsulates the change somehow

Sam, his producer and his markerting manager have just wrapped show number 56, they are down due to the gloomy issues, they are down because they are facing climate change, they are down because they have just had a guest breakdown and sob and cry on their live show.

"That was real, man, so real. I'm not sure why we don't have an audience connecting, we're focusing on very real issues and talking about it in a candid, none bullshit way that tears down the artifice and digs deep into the depths of the conversation," says Sam.

"You know, maybe not everybody wants to listen to a downer podcast with their morning coffee right, when they're going to work in the morning?" his producer Matt follows up. "I mean it's heavy stuff man, like that was heavy, I actually think I have to call my fucking therapist right now, jesus christ."

Marketer speaking marketing speak; "Listener completion is down, our last sponsor has dropped us, we're negative 80k here. We're spending and targeting across all social channels but we're just not getting eyeballs to the stay on. We may have to pivot to a different messaging here. This is nothing new but climate change is not sexy, and it's not popular, and it's not new. Everyone knows everything about it already, it's gotten front page treatment for the twenty years."
# Have to find way to do corporate speak here, saying lot's of negative things but super optimistic maybe

"I thought if they could connect not just with the facts, but also the repercussions and the people behind the science there would be more of a impact."

# Maybe the scene should be of them planning meeting after their last show, which was the most successful ever, and it had not to do with climate science but with a doomsday prepper, and they actually made money because there is a lot you can sell by being a prepper.  They have sponsors who are interested, they actually decide to follow this route and they talk to a few companies that build bunkers
# The conflict is the producer wants to do more of prepper material, but Sam doesn't
# This is all planning, less fucking planning and more fucking writing

"Our last show went fucking viral, we actually made money on it because of all the affliate links. We need to do more of that Sam, that's the path," Matt is pumping his fist in excitement. After almost a year of weekly production with 54 hour long shows, all the hours and effort devoted to it, the last show was when they finally broke through. After seeing no progress, no growth or influence for a year, finally having a somewhat successful podcast episode was gratifying in a deep way.

"I mean people want to listen to this shit, they don't want to hear about climate feedback loops, and government policy and wonky stuff like that. They want the to hear about the doomsday bunker of the rich and fucking famous. Do you think there's a way we can get the company that built Matt Damon's bunker to talk about it on the show?"

# After a show where they interview bunker builders, and their ratings are actually climbing.  Sam goes shopping or something or sees something very mundane, it's like the subway or how people are just looking out for themselves, and it all becomes clear to him that when shit hits the fan people will revert to their most basic instincts, he sees it in technicolor in this random trivial moment somehow, maybe it's in a bar or something.  That's when he just goes all in on becoming a prepper, or maybe it's when he's driving on the freeway in a traffic jam
# But it's also how Sam is influenced by his enviornment, he's surrounded himself with prepper ideas because of his podcast and now that's what he sees and believes

"That's not the mission Matt," Sam says, "the show's mission is to educate, engage, and move the public towards specific policy action that will have an effect on net carbon emission."

Matt rolls his eyes and feigns a yawn, "If you have an audience of zero, it doesn't matter how lofty your goals are. None of it will matter. If we have an audience, if we're successful then we can actually affect change Sam. What have we actually accomplished in the last year?"

"We managed to burn through a shit ton of money is what we did," Sam replied at a loss for something concrete he could point to, something he could say that they had accomplished, he wanted to look through his KPIs and his metrics but he knew that there the podcast previously was a failure, a disaster really, with subscriber numbers in the teens, weekly listener numbers in the sigle digits, and abysmal completion rates. Even with the additional marketing budget, the Getting Real About Climate Change podcast was just getting off the ground. They had tried everythign, t-shirt and shit giveaways, cross promotion with local shops with coupons, live call-in sessions, photo ops, nothing it seemed could get this off the ground.

* Sam prepares for the collapse
# Cut everything below or rework, go straight to "construction of bunker"

It was the obvious and most rational thing to do really. If you could not change the course of things, if you can't even affect the perspective and lives of your immediate family members much less your government, country, if things are not going to change and they did not seem to be, then it only makes sense to take the necessary precautions to get yours and fuck the rest.
# I'm just trying to get mine, and he trying to get his... Hip hop quotes here would be good, it's the law of the jungle

It was obvious he had to move out of California, the wildfires, the depletion of the water table, and everything just cost too much here, he could easily blow through a couple of million and not get really anywhere.

# Wonder if there's a point to adding a section where a climate refugee meets with Sam, maybe he is doing activism and they meet and he interviews him for his own self interest, possibly pulling this from real reports

# Idea about Sam meeting someone while he is trying activism someone who he falls for? And where does this go? She can be the true ratinonal voice who refuses to go, and there is also the scientist consultant, those will be voices and dialectic in the story

Sam quickly realized that he had to keep complete secrecy on the bunker, once anyone knew then he would become a possible target or refuge when shit hits the fan, if he decided to take refugees or any other people into the bunker to carrying capacity would have to be doubled, then tripled and things could easily sprial out of control.
# Cut

Construction of the bunker was surprisingly the easiest part of the process [everything else is hard but consumerism is easy, like activism, collectivism, permaculture, real life is messy], once he began researching it, he found dozens of contruction and consulting companies catering to this demand. In a lot of cases they had done the background research and ran simulation scenarios using the cutting edge climate models. Sam picked the company rumored to have built Peter Thiel's New Zealand complex, they had beautiful powerpoints and brochures for each income bracket or sales brackets, of course they did not advertise it as such, but were named after the 5 rarest metals in the universe; zircon, selenium, etc., Sam selected the Selenium packages at a cost of $80 million dollars. It was the single most expensive thing he had ever purchased.

Shockproof was the company name, maybe or Forevermore from Poe? Maybe after the 300 story of the romans something reminiscent of that.
# Maybe add how he joins a private slack or discord group that discusses this
# There's a whole underworld of markets, and climate change collapse world that Sam did not know existed
# Someone on the discord group gives him a referral, the company vets him, then contacts him, show it in a quick way

The bunker would take 4 years to build, would have electrostatic air filtration for nuclear fallout, geo-thermal heatpump and a backup propane system, a difference engine for the electricity storage, internal agricultural complex, indoor swimming pool, structural integrity tested up to 9+ on richter scale, and a storage silo to house enough food for up to 20 years for a single individual. Sam could have upgraded this to 10 or 12 years but there was a warranty that expired after the 6th year so he didn't. He knows that it doesn't make sense to have a warranty expiring for societal and ecological collapse.
# Do some research or cut this like I don't even want to read this section

For security there were 6 cybernaetic dog bots with machine guns, their facial recognition was a bit buggy he'd heard but they were rolling out a new patch shortly that would fix everything.
# Expand slightly, add how Sam plays fetch with them

There was a car that didn't have any input controls, it was all voice acitivated and self driving, it seemed a but strange... *wasn't the point of being human to control things and machines?*

# The bunker is a smart device operated by an ai assistant, after the world war the ai goes crazy and Sam has to disable it

* Fail safe
"The bunker is fail safe and guaranteed to last for over 100 years," she was saying. It was a business lunch, the company had scheduled an final sales lunch where Sam would sign the sales contract and the rep would answer any questions.

Rhodium
Palladium
Gold
Iridium
Platinum

Sam's lawyer and his collapse consultant had already reviewed the documents. He had spent two days reviewing the final plans with Richard the collapse consultant. Reviewing the daily caloric inputs and collating that with the food storage silos.

They went over the possible power loss and back ups, the fail safes and alternates that they planned for. This was six sigma functional tolerance stress tested, every failure point was considered and multiple back ups and or alternates planned for.
# All of this is kinda boring and beside the point, now that I'm reading it over
# I understand that it was necessary to write this in V0 as your thinking it through but just not interesting because it's not about the story
# Basically need to expand details that have to do with the story and cut everything else

# Maybe add an single example of this and they talk over it and imply everything else. They have an argument about something, some small petty esoteric detail that expanse to something bigger or shows how far in they've gotten into the weeds

# What's the very human thing that Sam doesn't account for? Let's make it about people and connections but how can I make it work? Like he's a tech It's funny, this is like the point of the story, the crux of it and I have spent zero time thinking about it...

* Collapse
In the end it wasn't anything spectacular, it was kind of a let down. Eight hundred years of western civilization, all the triumphs of science could not get around a very simple physical principal of the carbon molecule and photons. It was simply, deliciously ironic. William Gibson was right of course: "the future is already here, it's just unevenly distributed." [This would be the connection to the climate refugee character if he is added]. It was the same things that had happened in Subsarahan Africa [add examples and countries and have notes to articles]. It was just bigger and the collapse unfurled headlong like a stumbling uncoordinated five year old tantrum that raged across the US and the western hemishpere like a cloud of unknowing.

It happened, but no one could really say when it happened. The truth was that it had been happening all along. The seed was in the beginning. The logic was irrevocable. The crop failures started, prices of basic staples shot up, things started to get a bit edgy. You heard distantly like you always do about some government falling, some famines somewhere, then you wake up and walk out to get a morning cup of coffee and the collapse is at your doorstep. There are lines at the gas station, the coffee shop is closed, and you see a wall of smoke and flames coming towards you from the west whipped up by the santa maria winds. And it's not like in any movie, it's hyper real in a surreal dream like way impossible to describe. It was like something you've seen before, it starts to crack and bend, then all of a sudden the damn breaks and it's over and done.

As Sam was watching the destabilization he had anticipated and prepared for five years unfold around him, he didn't know when he should head into the bunker, was it just going to continue like this for years? They say it took Rome a hundred years to fall but that the final sack only took a day.
# Research above facts
# I think I need to stay as close as possible to POV of Sam and make it into his story, I read all this 3rd person narration and most of it is boring, even though there are some words and phrases that hit
But this wasn't the fall of an empire, it was the fall of human civilization as we knew it, it was the collapse of the stable climate regime that life itself had depended on for the past millenia. Sam watched but did not know when to engage the plan, the plan he called: "Operation Popcorn," as in let's pop this cornstand.
# Can add the private discord chats here, all the preppers talking about when to pull the plug

# Sam's girlfriend refuses to leave, he tries to convince her but she refuses. This doesn't really carry the point of the original idea across does it? Did have this thought that he cuts corners, and does the calculation and decides that the resources needed for 2 people will drastically shorten the life carrying span of the bunker. It should be like a decision he makes, it's a symptom of man's blindness, a man's blindness to the interconnected reality of things. The interdependence of all things, maybe explore this buddhist idea further.

Sam finally decided to go in when the president stopped making public appearances and Taylor Swift cancelled her north american 'the look' tour, he figured if anything was a signal that was it.
# I like this, this is funny and unexpected

# Need to add scene when he finally travels to the bunker and closes it, saying goodbye to the world as he knew it
# It's the decision point and a significant transition
# Like I see him going to do some capitalist shit, he's coming out of the supermarket and someone is just robbing the supermarket with an AK-47 while you see the glow of the fires and the smoke is being whipped into your eyes and he thinks fuck, it's happened quickly

It was like all the movies and books you saved but never read because you didn't want to. It was the same kind of thinking that limited your ability anticipate. Sam really did not have any experience in deprivation or doing things alone. He did go glamping and to burning man but that was kinda it. He didn't know what it was like to go through a month on rations. Unfortunately for Sam, that planners and cooks of the Sellenium also did not account for the fickleness of the human mind and tastebuds. They were nutritionally rigorous, in that they were made to optimize storage and nutritional degradation without being frozen, taste and variety were secondary concerns.
# Rewrite and rework above

# Need a description of the collapse, kind of what happens and what are the consequences, maybe he has a chance to save more people but doesn't risk it

# !Maybe add how he has a calendar full of prepper stuff: at 1PM he has a shooting class at a gun range, at 9am he has a edible foraging tour, etc. and maybe just describe a scene and the people in it. It's just funny, but then he does something that's like the opposite of prepper, showing how hard it is to maintain consistency or something how unreal it is. Might make sense to do some real prepper research for this if it gets bigger but for now want to keep it short short short

* Sam chooses oblivion
# This is another pattern where in the beginning of the story I feel like I can see it and feel the filaments holding it together but after the middle part, I'm lost and I can't see it. In the beginning when I imagine it, I can see it like it's a movie or a graphic novel but after the start I just try to muddle along and get lost in tangents

# There's a conflict in my writing style proclivities and what I'm trying to do now... It's the tension between like more creative fiction and plot driven stories. The interior vs the action, where I almost need the interior to write or for anything to make sense, but it's not really necessary in a plot driven story

In the end, the collapse of farming and foodstocks caused the collapse of the financial system which eventually led to political conflict which escalated into loud talking, threats, war, and finally nuclear fallout. US fired the first round and China retaliated, obliterating the eastern coast and knocking out most of the nuclear missile silos across the US. The following nuclear winter that encircled the globe decimated any larger human population centers around the world and put earth into the 6th great extinction. Accelerating what was already locked in place by a factor of thousands of years. The US did not consider a full out retaliatory attack by China, most simulations and AI models suggested more posturing and threats. I guess they fucked around and found out.

Without the satellites, the technical infrastructure also collapsed immediately like a stack of cards, leaving the survivors isolated and unable to communicate, each man now truly was an island and a soveriegn onto himself.

Living alone 500 meters dug into the bedrock of the norther eastern Canadian granite, over 2 hundred miles from any human town or outpost; that was the plan, humans were the main threat to survival according to the collapse consultants, so one of the main priorities of the bunker had been remoteness. Now 2 years into bunker life, Sam had a few regrets.

Sam wished that he had splurged on the more expensive single origin vacuum sealed coffee beans, but they had been so expensive compared to the generic grounds, costing four times as much for pound and over 50 years the cost was astronomical and outrageous! But now his morning coffee was bitter and black, lacking any depth or complexity. The cold brew nitrous machine may have been worth the 12k as well, Sam thought and sighed as he sipped his coffee without any joy. It was the same with the rest of bunker life, it was mechanical and industrial and gray.

For the first month or two immediately after he had relocated to the bunker and sealed the entrance, he had been active, industrious; regularly going through his prescribed regiments and chores. There was a life optimization maintenance manual that came with a bunker, 2 copies in case one was lost or damaged. It was the size of a telephone book and had all the mechanical chores the occupant must engage in to maintain and keep the bunker in good shape so it would last for the warraty, a break in the maintentance schedule could null the warranty. But month after month of the same routine had worn on him and he had become slothful, dirty, and negligent.

There was an indoor hydronphonic vertical farm that Sam had started to neglect, the garbage bins had not been ejected and trash were piling up in the kitchen, the bedroom, everywhere. The air filter hadn't been swapped out and a full gas regeneration protocol had not been completed and so there was a staleness to the air that had been re-circulating the same molecules for weeks at a time. Things were beginning to fray.

Sam had imagined things differently in his mind. He definitely experienced some shaden-fraude in the beginning as he watched the events unfolding on satellite news. But now... now he was just bored, bored out of his mind.
# Above synopsis is ok but doesn't pop, how can I show the progression or orderly discipline and collapse the time frame in a dramatic way?
# There definitely needs to be an AI component or maybe not, it's too energy heavy to run

# This is just like the issue I had with previous story, it's not one thing or another, it's like in-between, it should be more extreme and surreal or more realistic and factual but it's just straddles a mediocre line inbetween (this is kind of a reflection of me I think). I'm also contantly telling and summarizing things vs. showing and creating scenes, it's like a beginning writers weakness. I mean what's memorable are the people and the action not the telling

Sam crying in the shower
Sam throwing a temper tantrum while doing a chore he doesn't want to do

The amount of things that had to be done and taken care of with the bunker was exhausting Sam thought. It wasn't something he was really used to, he had lived in apartments and condos all his life, always with a cleaning lady, and he definitely could not be bothered to cook. It wouldn't really be making optimal use of his time and talents, would it? There were people who were more suited to those types of tasks and he availed himself of their services and talents. His talent was more cerebral, more creative, and idea generation, his talent was why he was where he was and why they were where they were.

Sam unable to get up in the morning because there is no reason to
# This entire section needs to be tightened up
# What does it mean to be alone? What a man does when no one is looking is what he really is or some quote like that... and use it to mock Sam in a way

Of course he had considered all the issues and had a digital library larger than the library of congress (maybe something breaks and he can't access it, it's a network thing that no one considered), with over a million books, music, shows, and movies. He tried to read but could not concentrate, none of it seemed to make sense or was relevant at this juncture, "Deep Work," "How to increase productivity," "some other titles," including some fiction classics none of these spoke to what Sam was experiencing now.

He flips through a poem book but there is no nature here, and there is no future here. He runs across a quote and it hits him, he touches the screen but there's nothing to touch.
# Would like to find a poem that speaks to this condition and maybe quote it. See T.S. Eliot.
# Actually maybe I need to find a poem that speaks about love and the need for human connection and highlight that

Sam tries to watch a comedy but comedies or movies only work or mean anything in a larger context, it's embedded within the whole fabric, without it it's meaningless. Sam starts laughing at a show but then stops and throws the remote at it.
# Maybe the office or seinfeld?

# How can I empahsize and show the hyper material mechanical opportunistic calculating aspect of his mind? It also has to be part of his actions and what he does. It should involve his decision not to invite or tell his girlfriend, the flatness and capitalistic game theory of such a mind. Want to do this but don't want to spend too much time making it real, ugh. Contiunally coming back to DFW as a good example to copy and parody here, but also want to be me and find me and not try to be something else. I should just try to find my own way instead of looking outside right now

Sam watches videos from his iphone captured months before he left, it's a stupid video but he plays it over and over. In it, Natalie is across from him at a cafe table and she's looking off into right and feeding a cat that's just off camera.
# This is good maybe, need to detail or expand on this

Sam regrets a few things, and he doesn't want to keep this going any longer. His mind that runs around like a hamster and which he can't shut off. Sam realizes that meaning only comes from a connection to people. That's it. There is nothing else in the world. He doesn't want to live when there is nothing worth living for.
# Change this to make it implicit vs explicit

Sam opens up a bottle of champaign, he had imagined saving it at some future date, when he could reimerge into the world but that's no longer happening. He opens up a cyanide capsule and pours it into the flute glass taking a deep drink and he lays down to die, he welcomes the oblivion he worked so hard against, and death becomes a welcome reprieve from the thoughts he can't escape.
# Showcase Sam's liberatarian individualistic tendencies early in the story

The Selenium crew find him dead in his bedroom while they are doing monthly maintenance. The whole thing had been a simulation.

* There's something essential missing here, a drama, a turning I think something needs to happen with his relationship
He keeps this a secret, and she finds out, they fight and she walks off
She finds the bunker a ridiculous idea
Or maybe it's just an oversight or a blunder that he makes, not understanding his own human needs
A scene from a popular movie he's watching but it doesn't mean anything because there is no fucking future or people duh

# Sam feels like there's something that he's missing, a nagging feeling like he's forgotten something, like a dream that he can't remember
# Reading "Deluge" by Markley and it's throwing me for a loop here, it's like here's a thing that I could have done, here's a thing that I coulda been

* Cut

** Prelude
There is a wide spectrum of concern, awareness, and knowledge of the inexhortable effects of climate change and it's possible consequences in the general public. Most of us are sitting in the fat middle of the ditribution curve, vaguely worried, sometimes alarmed, but easily distracted by many other much more immediate concerns; does my wife still love me, what will I do about dinner, , does my child have RSV the new repsiratory virus and why isn't she getting better, and what is the little bumps on her face, and what about the fever the other day and how she was hallucinating and couldn't speak or describe anything because it was too crazy like she was having a mental breakdown, and the micro-plastics they found in everything including the placenta, should I be eating cheerios even though with the forever chemicals, and I have to rinse the bottles and get a metal straw so I'm not killing the loggerhead turtles, is the bird-flu jumping into mamal species with DNA traces being confirmed in pastuerizied milk something I need to pay attention to, and maybe I should start getting the ultra pasturized that come in the boxes that last forever you can find sometimes at the big box stores, and so on.

Maybe the problem is not the lack of political will, or cohesion, but rather the lack of attentional space that's part of modern digital life, in humanity's complete abdication of reason, duty, and simple survival common sense. Maybe it's not that we lacked the strength or foresight but that we were fragmented and distracted to madness.

This is a story about a man's journey from the concerned, but too busy really to think about it and what can I really do anyway, middle of the bell curve to the far end of climate change doomer and prepper extremism. This tale will not try to convince anyone of the reality of our present predicament or concern itself on the other fringe of climate change deniers... They can go eat shit really for all I care.
