* https://www.newyorker.com/magazine/2017/01/30/doomsday-prep-for-the-super-rich
Tim Chang, the venture capitalist who keeps his bags packed, told me, “My current state of mind is oscillating between optimism and sheer terror.”

A survey commissioned by National Geographic found that forty per cent of Americans believed that stocking up on supplies or building a bomb shelter was a wiser investment than a 401(k).

Hoffman said, “Saying you’re ‘buying a house in New Zealand’ is kind of a wink, wink, say no more. Once you’ve done the Masonic handshake, they’ll be, like, ‘Oh, you know, I have a broker who sells old ICBM silos, and they’re nuclear-hardened, and they kind of look like they would be interesting to live in.’ ”

* https://www.nytimes.com/2023/03/20/climate/global-warming-ipcc-earth.html
Climate Change Is Speeding Toward Catastrophe. The Next Decade Is Crucial, U.N. Panel Says.

There is still one last chance to shift course, the new report says. But it would require industrialized nations to join together immediately to slash greenhouse gases roughly in half by 2030 and then stop adding carbon dioxide to the atmosphere altogether by the early 2050s. If those two steps were taken, the world would have about a 50 percent chance of limiting warming to 1.5 degrees Celsius.

Delays of even a few years would most likely make that goal unattainable, guaranteeing a hotter, more perilous future.

“The pace and scale of what has been done so far and current plans are insufficient to tackle climate change,” said Hoesung Lee, the chair of the climate panel. “We are walking when we should be sprinting.”

Under the current policies of national governments, Earth is on pace to heat up by 2.1 to 2.9 degrees Celsius this century, analysts have estimated.

* https://tos.org/oceanography/article/is-the-atlantic-overturning-circulation-approaching-a-tipping-point

* https://www.nature.com/articles/s41467-023-42198-2
Rapid disintegration and weakening of ice shelves in North Greenland
The glaciers of North Greenland are hosting enough ice to raise sea level by 2.1 m, and have long considered to be stable. This part of Greenland is buttressed by the last remaining ice shelves of the ice sheet. Here, we show that since 1978, ice shelves in North Greenland have lost more than 35% of their total volume, three of them collapsing completely.
